server {
  listen 80;

  location /uploads/ {
    proxy_pass http://backend:8000/uploads/;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri /index.html =404;
  }

  include /etc/nginx/extra-conf.d/*.conf;
}