server {
  listen 80;

  resolver 127.0.0.11 valid=10s;

  location /uploads/ {
    set $backend_host backend;
    proxy_pass http://$backend_host:8000;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri /index.html =404;
  }

  include /etc/nginx/extra-conf.d/*.conf;
}