"""busroute_add_direction_timetable

Revision ID: b9e9b73603a8
Revises: e719cba32312
Create Date: 2026-04-23 19:15:04.687127

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b9e9b73603a8'
down_revision = 'e719cba32312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busroute', sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False))
    op.add_column('busroute', sa.Column('timetable_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_busroute_route'), table_name='busroute')
    op.create_index(op.f('ix_busroute_route'), 'busroute', ['route'], unique=False)
    op.create_unique_constraint('uq_busroute_route_direction', 'busroute', ['route', 'direction'])
    op.drop_column('busroute', 'frequency_minutes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busroute', sa.Column('frequency_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint('uq_busroute_route_direction', 'busroute', type_='unique')
    op.drop_index(op.f('ix_busroute_route'), table_name='busroute')
    op.create_index(op.f('ix_busroute_route'), 'busroute', ['route'], unique=True)
    op.drop_column('busroute', 'timetable_json')
    op.drop_column('busroute', 'direction')
    # ### end Alembic commands ###
