"""add_busroute

Revision ID: e719cba32312
Revises: 1a31ce608336
Create Date: 2026-04-23 17:53:33.073776

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e719cba32312'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busroute',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('first_bus', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('last_bus', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('trips_per_day', sa.Integer(), nullable=True),
    sa.Column('frequency_minutes', sa.Float(), nullable=True),
    sa.Column('stops_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_busroute_route'), 'busroute', ['route'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_busroute_route'), table_name='busroute')
    op.drop_table('busroute')
    # ### end Alembic commands ###
